crawler:
  target_num: 10
  user_agent: 'Mozilla/5.0'
  mail: 'euthanasia045@gmail.com'
  wait_sec: 0.1
  ext: 'png'

  for_expart:
    dropout_img_squares: False
    output_imglog: False
    parser: 'lxml'
    save_bin: False

ml:
  model: 'origin' # 'origin': originalNN in ./ml/network.py
  use_easymode: False # use ./network_easymode.py
  test_data_rate: 0.3
  grayscale: True
  img_size_xy: 100 # must 71 < num
  savemodel_ext: '.h5'

oppoimg:
  decay: 0.3
  mode: 'all'

predictapp:
  save_inferenced_img: True
